# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           /:month-:day-:year/:title.html
relative-permalink: true
permalink: pretty
highlighter:         true
safe: false

gems: [jekyll-paginate]

gems: [jekyll-paginate]

# Setup
title:               Juruo怎么写
tagline:             qwertier's blog
description:         qwertier's blog
paginate:            5

# About/contact
author:
  name:              Yukun Ma
  url:               http://www.qwertier.cn
  email:             gmayukun@gmail.com
