# Permalinks
#
# Use of 'relative_permalinks' ensures post links from the index work properly.
permalink:           pretty
gems:                [jekyll-paginate]

# Setup
title:               'JURUO怎么写'
tagline:             "qwertier's blog"
description:         '蒟蒻的学习思考'
url:                 'http://blog.qwertier.cn'
baseurl:             ''
paginate:            5
markdown:            kramdown
highlighter:         rouge

# About/contact
author:
  name:              'Yukun Ma'
  url:               'https://www.qwertier.cn'
  email:             'gmayukun@gmail.com'

github:
  repo:              'https://github.com/mayukuner/mayukuner.github.io/'

version:             '3.14'
